version: '2'

services:

  nginx:
    image: nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/nginx/vhost.d:/etc/nginx/vhost.d:ro
      - ./data/nginx/dhparam:/etc/nginx/dhparam:ro
      - ./data/letsencrypt/etc/letsencrypt:/etc/letsencrypt:ro
      - ./data/letsencrypt_challenges/:/var/www/letsencrypt:ro
